import React from "react";
import Header from "./Header";
import Footer from "./Footer";
import { Box } from "@chakra-ui/react";
import Head from "next/head";

interface ILayoutComponent {
  children: React.ReactNode;
}
const LayoutComponent: React.FC<ILayoutComponent> = ({ children }) => {
  return (
    <>
      <Head>
        <title>FishLog - Integrated Fisheries Technology Enabler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Box>
        <Header />
        <Box>{children}</Box>
        <Footer />
      </Box>
    </>
  );
};

export default LayoutComponent;
