import React, { useLayoutEffect } from "react";
import {
  Box,
  Container,
  HStack,
  Heading,
  Icon,
  SimpleGrid,
  Stack,
  Text,
  VStack,
  useColorMode,
} from "@chakra-ui/react";
import Head from "next/head";
import { CheckIcon } from "@chakra-ui/icons";

interface ILayoutComponent {
  children: React.ReactNode;
}

const LayoutComponent: React.FC<ILayoutComponent> = ({ children }) => {
  const { colorMode, toggleColorMode } = useColorMode();
  useLayoutEffect(() => {
    colorMode === "dark" && toggleColorMode();
  }, []);
  return (
    <>
      <Head>
        <title>
          Caker - Slice of Heaven: Indulge in the Finest Cake Delicacies
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Box p={4} mt={10}>
        <Stack spacing={4} as={Container} maxW={"3xl"} textAlign={"center"}>
          <Heading fontSize={"3xl"}>
            Slice of Heaven: Indulge in the Finest Cake Delicacies
          </Heading>
        </Stack>

        <Container maxW="8xl" mt={5}>
          {children}
        </Container>
      </Box>
    </>
  );
};

export default LayoutComponent;
